### PR TITLE
feat: Add --package to file paths

### PR DESCRIPTION
**Pull request by CelticMajora**
### 📰 Summary of changes

Ensures that the `--package` parameter gets added to file paths if it exists.

### 🧪 Testing done

Updated existing tests

### CODE REVIEW

**Review by samandmoore — APPROVED** [review]

**Comment by CelticMajora** [comment]
@Betterment/security We've intended to turn off n*nda for this repo, as we plan to publish it as a package, however even after removing it's access, it appears to keep stalking the repo. Any ideas on how to actually disable?

**Comment by CelticMajora** [comment]
@samandmoore << domain
/no-platform

**Comment by CelticMajora** [comment]
<< domain lgtm
<< platform lgtm

**Comment by samandmoore** [comment]
whoops

domainlgtm

**Pull request merged**
