### PR TITLE
chore: Update dependencies and README

### PR DESCRIPTION
**Pull request by CelticMajora**
### 📰 Summary of changes

- Add pub badge to README
- Update all dependencies to their most recent versions

### Reviewers

/domain @Betterment/better_test_reporter-maintainers
/no-platform

### CODE REVIEW

**Review by samandmoore — DISMISSED** [review]
<<domainlgtm 

Just gotta figure out why the coverage went down??

**Comment by CelticMajora** [comment]
Think some generated freezed magic under the hood made it so factory constructors that were called in the pass are no longer registering as covered 🤔

**Comment by CelticMajora** [comment]
bump nanda

Still not entirely sure why it started reporting factory constructors in freezed files as valid lines for coverage, but added in ignores to cover them. Only wrapped the factory constructors so that it should be clear to add anything else to these files outside of the ignore block. Will keep digging into the why 🤔

**Comment by CelticMajora** [comment]
bump nanda

Still not entirely sure why it started reporting factory constructors in freezed files as valid lines for coverage, but added in ignores to cover them. Only wrapped the factory constructors so that it should be clear to add anything else to these files outside of the ignore block. Will keep digging into the why 🤔

**Comment by samandmoore** [comment]
Weird!

**Comment by samandmoore** [comment]
<<domainlgtm

**Pull request merged**
